#基础配置
server:
  port: 8081

#dubbo配置
dubbo:
  application:
    name: dubbo-servic
  registry:
    address: 127.0.0.1:2181

#数据库配置
spring:
  datasource:
    name: snack
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      druid-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/snack?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: liurui
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liurui.entity
#mapper
mapper:
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



